version: '2'
services:
  app:
    container_name: python_app
    build: 
      context: ./docker/
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/app
      - ./csv:/var/www/csv
      - ./json:/var/www/json
      - ./xml:/var/www/xml
      - ./config:/var/www/config
